package com.byiara.api

import com.byiara.api.auth.domain.AdminRole
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.jooq.DSLContext
import org.jooq.impl.DSL.currentOffsetDateTime
import org.jooq.impl.DSL.field
import org.jooq.impl.DSL.name
import org.jooq.impl.DSL.table
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc
import org.springframework.security.crypto.password.PasswordEncoder
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.web.servlet.MockMvc
import org.springframework.test.web.servlet.MvcResult
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post
import org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath
import org.springframework.test.web.servlet.result.MockMvcResultMatchers.status

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class ByIaraApiApplicationTests {
	@Autowired
	private lateinit var mockMvc: MockMvc

	@Autowired
	private lateinit var dsl: DSLContext

	@Autowired
	private lateinit var passwordEncoder: PasswordEncoder

	@BeforeEach
	fun seedAdminUser() {
		dsl.execute(
			"""
			create table if not exists admin_users (
			    id uuid primary key,
			    email varchar(255) not null unique,
			    password_hash varchar(255) not null,
			    role varchar(40) not null,
			    active boolean not null,
			    created_at timestamp with time zone not null,
			    updated_at timestamp with time zone not null
			)
			""".trimIndent(),
		)

		dsl.execute(
			"""
			create table if not exists admin_login_attempts (
			    id bigint generated by default as identity primary key,
			    scope varchar(40) not null,
			    key_hash varchar(64) not null,
			    failed_at timestamp with time zone not null default now()
			)
			""".trimIndent(),
		)

		dsl.execute(
			"""
			create table if not exists refresh_tokens (
			    id uuid default random_uuid() primary key,
			    admin_user_id uuid not null,
			    token_hash varchar(64) not null unique,
			    expires_at timestamp with time zone not null,
			    revoked_at timestamp with time zone,
			    created_at timestamp with time zone not null default now()
			)
			""".trimIndent(),
		)

		val adminUsers = table(name("admin_users"))
		dsl.deleteFrom(table(name("admin_login_attempts"))).execute()
		dsl.deleteFrom(table(name("refresh_tokens"))).execute()
		dsl.deleteFrom(adminUsers).execute()
		dsl.insertInto(adminUsers)
			.columns(
				field(name("id")),
				field(name("email")),
				field(name("password_hash")),
				field(name("role")),
				field(name("active")),
				field(name("created_at")),
				field(name("updated_at")),
			)
			.values(
				field("random_uuid()"),
				"admin@by-iara.local",
				requireNotNull(passwordEncoder.encode("ChangeMe123!")),
				AdminRole.ADMIN.name,
				true,
				currentOffsetDateTime(),
				currentOffsetDateTime(),
			)
			.execute()
	}

	@Test
	fun contextLoads() {
	}

	@Test
	fun `health endpoint returns service status`() {
		mockMvc.perform(get("/health"))
			.andExpect(status().isOk)
			.andExpect(jsonPath("$.status").value("UP"))
			.andExpect(jsonPath("$.service").value("by-iara-api"))
	}

	@Test
	fun `admin login returns an access token`() {
		mockMvc.perform(
			post("/api/admin/auth/login")
				.contentType("application/json")
				.content("""{"email":"admin@by-iara.local","password":"ChangeMe123!"}"""),
		)
			.andExpect(status().isOk)
			.andExpect(jsonPath("$.accessToken").isString)
			.andExpect(jsonPath("$.refreshToken").isString)
			.andExpect(jsonPath("$.tokenType").value("Bearer"))
			.andExpect(jsonPath("$.expiresInSeconds").value(3600))
			.andExpect(jsonPath("$.admin.email").value("admin@by-iara.local"))
			.andExpect(jsonPath("$.admin.role").value("ADMIN"))
	}

	@Test
	fun `refresh token issues a new session`() {
		val refreshToken = refreshTokenFrom(login())

		mockMvc.perform(
			post("/api/admin/auth/refresh")
				.contentType("application/json")
				.content("""{"refreshToken":"$refreshToken"}"""),
		)
			.andExpect(status().isOk)
			.andExpect(jsonPath("$.accessToken").isString)
			.andExpect(jsonPath("$.refreshToken").isString)
			.andExpect(jsonPath("$.admin.email").value("admin@by-iara.local"))
	}

	@Test
	fun `reusing a rotated refresh token is rejected`() {
		val originalToken = refreshTokenFrom(login())

		// First refresh rotates the token (revoking the original).
		mockMvc.perform(
			post("/api/admin/auth/refresh")
				.contentType("application/json")
				.content("""{"refreshToken":"$originalToken"}"""),
		).andExpect(status().isOk)

		// Replaying the original (now-revoked) token is treated as reuse.
		mockMvc.perform(
			post("/api/admin/auth/refresh")
				.contentType("application/json")
				.content("""{"refreshToken":"$originalToken"}"""),
		)
			.andExpect(status().isUnauthorized)
			.andExpect(jsonPath("$.message").value("Invalid or expired refresh token"))
	}

	@Test
	fun `logout revokes the refresh token`() {
		val refreshToken = refreshTokenFrom(login())

		mockMvc.perform(
			post("/api/admin/auth/logout")
				.contentType("application/json")
				.content("""{"refreshToken":"$refreshToken"}"""),
		).andExpect(status().isNoContent)

		mockMvc.perform(
			post("/api/admin/auth/refresh")
				.contentType("application/json")
				.content("""{"refreshToken":"$refreshToken"}"""),
		).andExpect(status().isUnauthorized)
	}

	private fun refreshTokenFrom(result: MvcResult): String =
		Regex(""""refreshToken":"([^"]+)"""")
			.find(result.response.contentAsString)
			?.groupValues
			?.get(1)
			?: error("Missing refreshToken")

	@Test
	fun `admin login returns a signed JWT that can access protected admin routes`() {
		val loginResult = login()
		val response = loginResult.response.contentAsString
		val token = Regex(""""accessToken":"([^"]+)"""")
			.find(response)
			?.groupValues
			?.get(1)
			?: error("Missing accessToken")

		kotlin.test.assertEquals(3, token.split(".").size)

		mockMvc.perform(
			get("/api/admin/auth/me")
				.header("Authorization", "Bearer $token"),
		)
			.andExpect(status().isOk)
			.andExpect(jsonPath("$.email").value("admin@by-iara.local"))
			.andExpect(jsonPath("$.role").value("ADMIN"))
	}

	@Test
	fun `protected admin routes require a valid JWT`() {
		mockMvc.perform(get("/api/admin/auth/me"))
			.andExpect(status().isUnauthorized)
	}

	@Test
	fun `admin login rejects invalid credentials`() {
		mockMvc.perform(loginRequest(password = "wrong"))
			.andExpect(status().isUnauthorized)
			.andExpect(jsonPath("$.message").value("Invalid email or password"))
	}

	@Test
	fun `fifth failed login is rate limited with retry-after`() {
		repeat(4) {
			mockMvc.perform(loginRequest(password = "wrong"))
				.andExpect(status().isUnauthorized)
		}

		mockMvc.perform(loginRequest(password = "wrong"))
			.andExpect(status().isTooManyRequests)
			.andExpect(jsonPath("$.message").value("Too many login attempts. Try again later"))
			.andExpect { result ->
				kotlin.test.assertTrue(result.response.getHeader("Retry-After")!!.toLong() in 1..900)
			}
	}

	@Test
	fun `successful login resets the client-email failure window`() {
		repeat(4) {
			mockMvc.perform(loginRequest(password = "wrong"))
				.andExpect(status().isUnauthorized)
		}

		mockMvc.perform(loginRequest())
			.andExpect(status().isOk)

		repeat(4) {
			mockMvc.perform(loginRequest(password = "wrong"))
				.andExpect(status().isUnauthorized)
		}

		mockMvc.perform(loginRequest(password = "wrong"))
			.andExpect(status().isTooManyRequests)
	}

	private fun login(): MvcResult =
		mockMvc.perform(loginRequest())
			.andExpect(status().isOk)
			.andReturn()

	private fun loginRequest(
		email: String = "admin@by-iara.local",
		password: String = "ChangeMe123!",
		clientAddress: String = "203.0.113.10",
	): MockHttpServletRequestBuilder =
		post("/api/admin/auth/login")
			.with { request ->
				request.remoteAddr = clientAddress
				request
			}
			.contentType("application/json")
			.content("""{"email":"$email","password":"$password"}""")
}
