export const themeTokens = {
  name: 'by-iara',
  color: {
    background: 'var(--byiara-color-background)',
    surface: 'var(--byiara-color-surface)',
    surfaceMuted: 'var(--byiara-color-surface-muted)',
    surfaceTinted: 'var(--byiara-color-surface-tinted)',
    text: 'var(--byiara-color-text)',
    textMuted: 'var(--byiara-color-text-muted)',
    textSubtle: 'var(--byiara-color-text-subtle)',
    primary: 'var(--byiara-color-primary)',
    primaryHover: 'var(--byiara-color-primary-hover)',
    primaryStrong: 'var(--byiara-color-primary-strong)',
    primaryAction: 'var(--byiara-color-primary-action)',
    primaryActionHover: 'var(--byiara-color-primary-action-hover)',
    onPrimary: 'var(--byiara-color-on-primary)',
    primarySoft: 'var(--byiara-color-primary-soft)',
    primaryTint: 'var(--byiara-color-primary-tint)',
    accent: 'var(--byiara-color-accent)',
    accentSoft: 'var(--byiara-color-accent-soft)',
    onAccent: 'var(--byiara-color-on-accent)',
    border: 'var(--byiara-color-border)',
    borderSubtle: 'var(--byiara-color-border-subtle)',
    borderStrong: 'var(--byiara-color-border-strong)',
    borderRose: 'var(--byiara-color-border-rose)',
    focus: 'var(--byiara-color-focus)',
    danger: 'var(--byiara-color-danger)',
    dangerHover: 'var(--byiara-color-danger-hover)',
    success: 'var(--byiara-color-success)',
    warning: 'var(--byiara-color-warning)',
    info: 'var(--byiara-color-info)',
  },
  fontFamily: {
    sans: 'var(--byiara-font-family-sans)',
    display: 'var(--byiara-font-family-display)',
  },
  fontSize: {
    xs: 'var(--byiara-font-size-xs)',
    sm: 'var(--byiara-font-size-sm)',
    md: 'var(--byiara-font-size-md)',
    base: 'var(--byiara-font-size-base)',
    lg: 'var(--byiara-font-size-lg)',
    xl: 'var(--byiara-font-size-xl)',
    '2xl': 'var(--byiara-font-size-2xl)',
    '3xl': 'var(--byiara-font-size-3xl)',
    '4xl': 'var(--byiara-font-size-4xl)',
    '5xl': 'var(--byiara-font-size-5xl)',
  },
  lineHeight: {
    display: 'var(--byiara-line-height-display)',
    tight: 'var(--byiara-line-height-tight)',
    title: 'var(--byiara-line-height-title)',
    body: 'var(--byiara-line-height-body)',
    loose: 'var(--byiara-line-height-loose)',
  },
  spacing: {
    xs: 'var(--byiara-space-xs)',
    sm: 'var(--byiara-space-sm)',
    md: 'var(--byiara-space-md)',
    lg: 'var(--byiara-space-lg)',
    xl: 'var(--byiara-space-xl)',
    '2xl': 'var(--byiara-space-2xl)',
    '3xl': 'var(--byiara-space-3xl)',
    '4xl': 'var(--byiara-space-4xl)',
  },
  measure: {
    copy: 'var(--byiara-measure-copy)',
    narrow: 'var(--byiara-measure-narrow)',
  },
  radius: {
    sm: 'var(--byiara-radius-sm)',
    md: 'var(--byiara-radius-md)',
    lg: 'var(--byiara-radius-lg)',
    pill: 'var(--byiara-radius-pill)',
  },
  shadow: {
    sm: 'var(--byiara-shadow-sm)',
    md: 'var(--byiara-shadow-md)',
  },
  zIndex: {
    base: 'var(--byiara-z-index-base)',
    raised: 'var(--byiara-z-index-raised)',
    dropdown: 'var(--byiara-z-index-dropdown)',
    sticky: 'var(--byiara-z-index-sticky)',
    overlay: 'var(--byiara-z-index-overlay)',
    modal: 'var(--byiara-z-index-modal)',
    toast: 'var(--byiara-z-index-toast)',
    tooltip: 'var(--byiara-z-index-tooltip)',
  },
} as const;

export type ThemeTokens = typeof themeTokens;
export type ThemeColorToken = keyof ThemeTokens['color'];
